[mysqld] #indicate that config is to mysql
bind-address = 0.0.0.0 #config ip that server sql listen new connections
port = 3306 #port MySQL listen, 3306 is default use MySQL
socket = /run/mysqld/mysqld.sock #defines the location of the socket MySQL file
datadir = /var/lib/mysql #defines the dir where MySQL will alocate his database
log-error = /var/log/mysql/error.log #where MySQL save the errors logs
pid-file = /run/mysqld/mysqld.pid #where process pid is stored, this file allows the sistem know which process corresponds top  MySQL