[www] ;indicate that config is to www
user = www-data ;execute php with a normal user
group = www-data ;execute php with a normal group
listen = 9000 ;change listening port to allow Nginx connect with wordpres
listen.owner = www-data ;set socket owner to allow web server access
listen.group = www-data ;set socket group to allow web server access
pm = dynamic ;enable dinamic process management
pm.max_children = 5 ;max number of PHP process allowed
pm.start_servers = 2 ;number of processes created on start
pm.min_spare_servers = 1 ;keeps the projects managers on reserve in case a unexpected request arrivasl
pm.max_spare_servers = 3 ;same but establish max pms on reserve