user www-data; #indicate which system user run nginx processes
events {
    worker_connections 1024; #how many users can connect at the same time
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    #with this, if user try enter with http(port 80), force to use https(port443)
    server {
        listen 80;
        server_name ${DOMAIN_NAME};
        return 301 https://$host$request_uri;
    }

    #if entry with https
    server {
        listen 443 ssl http2;
        server_name ${DOMAIN_NAME};

        #define criptography, only accept TLSv1.2 TLSv1.3, olds versions have vulnerabilities
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;

        root /var/www/html;
        index index.php index.html;
        client_max_body_size 64M;

        #security headers
        add_header X-Frame-Options "SAMEORIGIN"; #avoid clickjacking
        add_header X-Content-Type-Options "nosniff"; #force use Content-Type offered by server
        add_header X-XSS-Protection "1; mode=block"; #if detect attack, no display web 

        #the way in which archives are handled
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        #catch all petitions which finish in .php
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        #block for security the files hidden that begin with .ht(.htons, .htacces)
        location ~ /\.ht {
            deny all;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ { #no distinguish between mayus or minus
        expires 1M; #save in cache max 1 month
        access_log off; #no have this petitions on logs
        add_header Cache-Control "public"; #can be acced the nav, proxies...
        }
    }
}